" dwm.vim mapping
nnoremap <C-J> <C-W>w
nnoremap <F12> <C-W>w
nnoremap <C-K> <C-W>W
nmap <C-T> <Plug>DWMRotateClockwise
nmap <C-Q> <Plug>DWMRotateCounterclockwise
nmap <C-N> <Plug>DWMNew
nmap <C-C> <Plug>DWMClose
nmap <C-@> <Plug>DWMFocus
nmap <f10> <Plug>DWMFocus
nmap <C-L> <Plug>DWMGrowMaster
nmap <C-H> <Plug>DWMShrinkMaster
nmap <BS>  <Plug>DWMShrinkMaster
