autocmd FileType markdown,howm_memo.markdown setlocal conceallevel=2
let g:markdown_fenced_languages = [
      \ 'coffee',
      \ 'cpp',
      \ 'css',
      \ 'diff',
      \ 'erlang',
      \ 'go',
      \ 'haskell',
      \ 'html',
      \ 'java',
      \ 'javascript',
      \ 'lua',
      \ 'ocaml',
      \ 'perl',
      \ 'plantuml',
      \ 'python',
      \ 'ruby',
      \ 'sh',
      \ 'sql',
      \ 'typescript',
      \ 'vim',
      \ ]
