#!/usr/bin/perl
use strict;
use warnings;

my $my_local = $ENV{MY_PERL_LOCAL_LIB} || '';
my $local = $ENV{PERL_LOCAL_LIB_ROOT} || '';
if ($local) {
    $local =~ s!$my_local!!g;
    $local = " - $local";
}

print "[$ENV{PERLBREW_PERL}$local]";
