"source $VIMRUNTIME/delmenu.vim " メニューを表示しない

set ambiwidth=single            " 文字幅が曖昧なときは半角と見なす
set printfont=Ricty_Discord:h10 " 印刷用フォント
set printoptions=number:y       " 印刷時に行番号を付ける
set visualbell                  " ビープ音を使わず画面をフラッシュさせる
set iminsert=0                  " インサートモードの初期値は IME OFF
set imsearch=-1                 " 挿入モードの初期値は iminsert に従う
set mouse=a                     " あらゆる場面でマウスを有効化
set clipboard=                  " クリップボードのオプションはなし
set guioptions=A                " モードレスセレクションに対する自動選択
set title                       " ウィンドウタイトルを更新する

if has('win32')
  set guifont=Ricty_Discord:h12
  set guifontwide=Ricty_Discord:h12
  set dir=$TEMP
  set backupdir=$TEMP
  set undodir=$TEMP
  set renderoptions=type:directx,gamma:1.8,contrast:1,level:1,geom:0,renmode:5,taamode:1
  set linespace=0                 " 行間を空けない

elseif has('macunix')
  let resolution = system("osascript -e 'tell application " . '"Finder"' . " to get bounds of window of desktop' | awk -F', ' '{print $3}'")
  if resolution < 1440
    set lines=50 columns=50         " ウィンドウの大きさを指定する
    set guifont=Ricty_Discord:h14
    set guifontwide=Ricty_Discord:h14
  else
    set lines=92 columns=190        " ウィンドウの大きさを指定する
    set guifont=Ricty_Discord:h14
    set guifontwide=Ricty_Discord:h14
  endif
  set linespace=0
  set antialias                     " 文字をなめらかに表示する
  set fuoptions=maxvert,maxhorz     " フルスクリーン時に表示を拡張
  set macmeta                       " option キーを alt キーとして使う
  set transparency=5                " 画面を半透明にする
  let $SUDO_ASKPASS=$SSH_ASKPASS
  let $DISPLAY=':0'
endif


"colorscheme desert-warm-256
"colorscheme bubblegum
"colorscheme neon-PK
"colorscheme zenburn
"colorscheme papayawhip
"colorscheme gummybears
"colorscheme void
"colorscheme badwolf
"colorscheme festoon
colorscheme solarized
"colorscheme gruvbox
"colorscheme plum
"colorscheme hemisu
"colorscheme briofita
"colorscheme hybrid
"colorscheme iceberg
"colorscheme badwolf
"colorscheme pencil
