scriptencoding 'utf-8'

if &compatible
  " vint: -ProhibitSetNoCompatible
  set nocompatible
  " vint: +ProhibitSetNoCompatible
endif

set runtimepath+=$HOME/.vim,$HOME/.vim/after
let s:source_rc = 'source ' . $HOME . '/.vim/rc/'
let s:load_rc = {file -> execute(s:source_rc . file . '.vim')}

call s:load_rc('vimrc')               " $VIM/vimrc から抽出した設定
call s:load_rc('dein')                " プラグインの読み込み
call s:load_rc('map')                 " マッピング
call s:load_rc('set')                 " オプション設定
call s:load_rc('term')                " ターミナル固有の設定
call s:load_rc('commands')            " ユーティリティコマンド

" デフォルトプラグインを無効化
let g:loaded_getscriptPlugin = 1
let g:loaded_logiPat = 1
let g:loaded_rrhelper = 1
let g:loaded_vimballPlugin = 1
if ! has('gui_running')
  let g:plugin_scrnmode_disable = 1
endif

" ローカル設定
let s:local_vimrc = $HOME . '/.vimrc-local'
if filereadable(s:local_vimrc)
  execute 'source ' . s:local_vimrc
endif
