local wezterm = require "wezterm"
local act = wezterm.action

return function(config)
  config.keys = {
    { key = "-", mods = "CMD", action = act.DecreaseFontSize },
    { key = "0", mods = "CMD", action = act.ResetFontSize },
    { key = "1", mods = "CMD", action = act.ActivateTab(0) },
    { key = "2", mods = "CMD", action = act.ActivateTab(1) },
    { key = "3", mods = "CMD", action = act.ActivateTab(2) },
    { key = "4", mods = "CMD", action = act.ActivateTab(3) },
    { key = "5", mods = "CMD", action = act.ActivateTab(4) },
    { key = "6", mods = "CMD", action = act.ActivateTab(5) },
    { key = "7", mods = "CMD", action = act.ActivateTab(6) },
    { key = "8", mods = "CMD", action = act.ActivateTab(7) },
    { key = "9", mods = "CMD", action = act.ActivateTab(8) },
    { key = "=", mods = "CMD", action = act.IncreaseFontSize },
    { key = "[", mods = "CMD", action = act.ActivateCopyMode },
    { key = "[", mods = "SHIFT|CMD", action = act.ActivateTabRelative(-1) },
    { key = "]", mods = "SHIFT|CMD", action = act.ActivateTabRelative(1) },
    { key = "`", mods = "CMD", action = act.ActivateWindowRelative(1) },
    { key = "c", mods = "CMD", action = act.CopyTo "Clipboard" },
    { key = "f", mods = "CMD", action = act.Search { CaseSensitiveString = "" } },
    { key = "f", mods = "CTRL|CMD", action = act.ToggleFullScreen },
    { key = "h", mods = "CMD", action = act.HideApplication },
    { key = "j", mods = "SHIFT|CMD", action = act.ActivatePaneDirection "Next" },
    { key = "k", mods = "SHIFT|CMD", action = act.ActivatePaneDirection "Prev" },
    { key = "l", mods = "CMD", action = act.ShowDebugOverlay },
    { key = "m", mods = "CMD", action = act.Hide },
    { key = "n", mods = "CMD", action = act.SpawnCommandInNewWindow { args = { "/opt/homebrew/bin/fish" } } },
    { key = "p", mods = "CMD", action = act.ActivateCommandPalette },
    { key = "r", mods = "CMD", action = act.ReloadConfiguration },
    { key = "r", mods = "SHIFT|CMD", action = act.ActivateKeyTable { name = "resize_pane", one_shot = false } },
    { key = "s", mods = "SHIFT|CMD", action = act.SplitVertical { args = { "/opt/homebrew/bin/fish" } } },
    { key = "t", mods = "CMD", action = act.SpawnCommandInNewTab { args = { "/opt/homebrew/bin/fish" } } },
    { key = "u", mods = "CMD", action = act.QuickSelect },
    { key = "v", mods = "CMD", action = act.PasteFrom "Clipboard" },
    { key = "v", mods = "SHIFT|CMD", action = act.SplitHorizontal { args = { "/opt/homebrew/bin/fish" } } },
    { key = "w", mods = "CMD", action = act.CloseCurrentTab { confirm = false } },
    { key = "z", mods = "SHIFT|CMD", action = act.TogglePaneZoomState },
  }
end
