#!/usr/bin/perl
use 5.30.0;
use feature qw(signatures state);
use warnings;
no warnings qw(experimental::signatures);

use Path::Tiny qw(path tempfile);

my $tmpl = path('tampermonkey/auto_pagerize.js.tmpl');
my $target = path('tampemonkey/auto_pagerize.js');
my $url = "http://wedata.net/databases/AutoPagerize/items_all.json";

die "tmpl not found: $tmpl" unless -f $tmpl;

my $tmp = tempfile;
0 == system 'sh', '-c', "curl -L $url > $tmp" or die "curl failed: $!";
(my $output = $tmpl->slurp) =~ s/"%__SITEINFO__%"/$tmp->slurp/e;
$target->spew($output);
