---
- name: prepare AquaSKK config dir
  file: path='~/Library/Application Support/AquaSKK' state=directory

- name: symlink keymap for AquaSKK
  file: >-
    src={{ dotfiles_dir }}/.config/AquaSKK/keymap.conf
    dest='~/Library/Application Support/AquaSKK/keymap.conf'
    state=link
    force=yes

- name: symlink kana-rule for AquaSKK
  file: >-
    src={{ dotfiles_dir }}/.config/AquaSKK/kana-rule.conf
    dest='~/Library/Application Support/AquaSKK/kana-rule.conf'
    state=link
    force=yes

- git: >-
    repo=https://{{ item }}
    dest=~/git/{{ item }}
  with_items:
    - github.com/KeenS/SKK_JISYO.wiktionary
    - github.com/uasi/skk-emoji-jisyo
    - github.com/ymrl/SKK-JISYO.emoji-ja
    - github.com/skk-dev/dict
    - github.com/tokuhirom/jawiki-kana-kanji-dict

- homebrew: >-
    name=skktools
    state=latest

- name: generate dictionary for shikakugoma
  shell: skkdic-expr SKK_JISYO.shikakugoma | skkdic-sort > ~/Library/Application\ Support/AquaSKK/SKK_JISYO.shikakugoma
  args:
    executable: /bin/bash
    chdir: ~/git/github.com/KeenS/SKK_JISYO.wiktionary

- name: copy emoji dictionary
  copy: >-
    src=~/git/github.com/uasi/skk-emoji-jisyo/SKK-JISYO.emoji.utf8
    dest='~/Library/Application Support/AquaSKK/SKK-JISYO.emoji.utf8'
    force=yes

- name: copy emoji-ja dictionary
  copy: >-
    src=~/git/github.com/ymrl/SKK-JISYO.emoji-ja/SKK-JISYO.emoji-ja.utf8
    dest='~/Library/Application Support/AquaSKK/SKK-JISYO.emoji-ja.utf8'
    force=yes

- name: copy jawiki dictionary
  copy: >-
    src=~/git/github.com/tokuhirom/jawiki-kana-kanji-dict/SKK-JISYO.jawiki
    dest='~/Library/Application Support/AquaSKK/SKK-JISYO.jawiki.utf8'
    force=yes

- name: convert some dictionaries
  shell: iconv -f EUC-JISX0213 -t UTF-8 ~/git/github.com/skk-dev/dict/{{ item }} > ~/Library/Application\ Support/AquaSKK/{{ item }}.utf8
  with_items:
    - SKK-JISYO.fullname
    - SKK-JISYO.JIS3_4
    - SKK-JISYO.JIS2004
    - SKK-JISYO.itaiji.JIS3_4
