---
- name: make content for client config
  copy: >-
    dest={{ secret_client_config.filename }}
    content={{ secret_client_config.json }}
  no_log: true

- name: ensure ~/.aws exists
  file:
    path: ~/.aws
    state: directory
    mode: "0700"
- name: make config for AWS
  template:
    src: aws-config.j2
    dest: ~/.aws/config
    mode: "0600"
  no_log: true
