require'agrp'.set{
  my_ftdetect = {
    {'BufNewFile,BufRead', '*.gs,.amethyst ', [[set filetype=javascript]]},
    {'BufNewFile,BufRead', '*.jbuilder ', [[set filetype=ruby]]},
    {'BufNewFile,BufRead', '*/nginx* ', [[set filetype=nginx]]},
    {'BufNewFile,BufRead', '*.m ', [[setf objc]]},
    {'BufNewFile,BufRead', '*.h ', [[setf objc]]},
    {'BufNewFile,BufRead', '*pentadactylrc*,*.penta ', [[set filetype=pentadactyl]]},
    {'BufNewFile,BufRead', '*.t', [[call delphinus#perl#test_filetype()]]},
    {'BufNewFile,BufRead', '*.xt', [[call delphinus#perl#test_filetype()]]},
    {'BufNewFile,BufRead', '*', [[if getline(1) =~ '^.*startuml.*$'|  ', [[setfiletype plantuml | endif]]},
    {'BufNewFile,BufRead', '*.psgi ', [[set filetype=perl]]},
    {'BufNewFile,BufRead', '*.pu,*.uml,*.plantuml ', [[setfiletype plantuml]]},
    {'BufNewFile,BufRead', '*.conf', require'ftdetect'.tmux},
    {'BufNewFile,BufRead', '*.tt2 ', [[setf tt2html]]},
    {'BufNewFile,BufRead', '*.tt ', [[setf tt2html]]},
    {'BufNewFile,BufRead', '.zpreztorc ', [[setf zsh]]},
    {'BufNewFile,BufRead', '*.plist,*.ttx ', [[setf xml]]},
    {'BufNewFile,BufRead', '*.applescript', [[setf applescript]]},
    {'BufNewFile,BufRead', '*.cc', [[setf cpp]]},
    {'BufNewFile,BufRead', '*.cpp', [[setf cpp]]},
    {'BufNewFile,BufRead', '*.cxx,*.c++,*.hh,*.hxx,*.hpp,*.ipp,*.moc,*.tcc,*.inl', [[setf cpp]]},
    {'BufNewFile,BufRead', '*.h', [[call dist#ft#FTheader()]]},
  },
}
