vim.keymap.set("n", "<C-i>", "O", { buffer = true })
vim.keymap.set("n", "<A-b>", "o", { buffer = true })
vim.keymap.set("n", "<A-∫>", "o", { buffer = true })
vim.keymap.set("n", "<C-o>", "o", { buffer = true })
vim.keymap.set("n", "<C-c>", "q", { buffer = true })
vim.keymap.set("n", "<CR>", "q", { buffer = true })
vim.keymap.set("n", "<Esc>", "q", { buffer = true })
